### ISSUE TITLE
can not run “user configure.mykeymap” 

### ISSUE THREAD

**Issue by yannisxu** [kojinho10/ExcelLikeVim#3]
![excel vim](https://user-images.githubusercontent.com/700891/36529966-cc822752-17f4-11e8-863a-105776ea1d1e.png)

**Comment by kjnh10** [comment]
Now the program assumes that "<YOUR HOME>/vimx/user_configure.bas" exists.
Please try to make an empty file in the above place.

Later I will modify the logic to work if the setting file does not exist.

**Comment by Aquafina-water-bottle** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/17107540/37178497-e8eae924-22df-11e8-8cf6-814cdaf7b6a3.png)
I am using the newest version (2.3.2), I have made a `user_configure.bas` under both `C:\vimx` and `~\ExcelLikeVim-2.3.2\vimx`, with the vimx.xlam file being under `~\ExcelLikeVim-2.3.2`.

**Comment by kjnh10** [comment]
Could you try to put vimx/user_configure.bas under your home directory?

**Comment by Aquafina-water-bottle** [comment]
I made a new file under `C:\Users\<username>\vimx\user_configure.bas`, and the error is still present.

**Comment by Aquafina-water-bottle** [comment]
Update: I copied/pasted the stuff in the example user_configure.bas file, and it seems like it is working now. Thanks!
